// <auto-generated />
using System;
using BettingSpreadsheet.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BettingSpreadsheet.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210419165313_User")]
    partial class User
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BettingSpreadsheet.Shared.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BetCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bookie")
                        .HasColumnType("TEXT");

                    b.Property<double>("ClosingOdds")
                        .HasColumnType("REAL");

                    b.Property<string>("League")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("MatchTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Odds")
                        .HasColumnType("REAL");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sport")
                        .HasColumnType("TEXT");

                    b.Property<double>("Stake")
                        .HasColumnType("REAL");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipster")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipsterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipsterId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BetCreated = new DateTime(2021, 4, 19, 18, 53, 13, 122, DateTimeKind.Local).AddTicks(3340),
                            Bookie = "Norsk-Tipping",
                            ClosingOdds = 3.25,
                            League = "Premier League",
                            Locked = false,
                            Match = "Manchester City v Arsenal",
                            MatchDate = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new TimeSpan(679931223260),
                            Odds = 3.5,
                            Selection = "Arsenal -0.5 Asian Handicap",
                            Sport = "Football",
                            Stake = 2.0,
                            State = "New",
                            Tipster = "Benny"
                        },
                        new
                        {
                            Id = 2,
                            BetCreated = new DateTime(2021, 4, 19, 18, 53, 13, 122, DateTimeKind.Local).AddTicks(9420),
                            Bookie = "Pinnacle",
                            ClosingOdds = 1.8,
                            League = "Premier League",
                            Locked = true,
                            Match = "West Ham v Fulham",
                            MatchDate = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new TimeSpan(679931229410),
                            Odds = 1.8400000000000001,
                            Selection = "Fulham +0.5 Asian Handicap",
                            Sport = "Football",
                            Stake = 5.0,
                            State = "New",
                            Tipster = "Benny"
                        },
                        new
                        {
                            Id = 3,
                            BetCreated = new DateTime(2021, 4, 19, 18, 53, 13, 122, DateTimeKind.Local).AddTicks(9440),
                            Bookie = "Unibet",
                            ClosingOdds = 3.25,
                            League = "Premier League",
                            Locked = true,
                            Match = "Liverpool v Leicester",
                            MatchDate = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new TimeSpan(679931229430),
                            Odds = 2.75,
                            Selection = "Leicester -0.5 Asian Handicap",
                            Sport = "Football",
                            Stake = 3.2000000000000002,
                            State = "New",
                            Tipster = "Sondreg"
                        },
                        new
                        {
                            Id = 4,
                            BetCreated = new DateTime(2021, 4, 19, 18, 53, 13, 122, DateTimeKind.Local).AddTicks(9440),
                            Bookie = "Norsk-Tipping",
                            ClosingOdds = 3.25,
                            League = "Premier League",
                            Locked = false,
                            Match = "Tottenham v Manchester Untited",
                            MatchDate = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new TimeSpan(679931229440),
                            Odds = 1.5,
                            Selection = "Manchester United -0.5 Asian Handicap",
                            Sport = "Football",
                            Stake = 8.0,
                            State = "New",
                            Tipster = "BookieInsider"
                        });
                });

            modelBuilder.Entity("BettingSpreadsheet.Shared.Bookie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Results")
                        .HasColumnType("REAL");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bookie");
                });

            modelBuilder.Entity("BettingSpreadsheet.Shared.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Results")
                        .HasColumnType("REAL");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sport");
                });

            modelBuilder.Entity("BettingSpreadsheet.Shared.Tipster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountStaked")
                        .HasColumnType("REAL");

                    b.Property<int>("BetCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("ROI")
                        .HasColumnType("REAL");

                    b.Property<double>("StartBank")
                        .HasColumnType("REAL");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tipster");
                });

            modelBuilder.Entity("BettingSpreadsheet.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<bool>("Public")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BettingSpreadsheet.Shared.Bet", b =>
                {
                    b.HasOne("BettingSpreadsheet.Shared.Tipster", null)
                        .WithMany("Bets")
                        .HasForeignKey("TipsterId");

                    b.HasOne("BettingSpreadsheet.Shared.User", null)
                        .WithMany("Bets")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BettingSpreadsheet.Shared.Bookie", b =>
                {
                    b.HasOne("BettingSpreadsheet.Shared.User", null)
                        .WithMany("Bookies")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BettingSpreadsheet.Shared.Sport", b =>
                {
                    b.HasOne("BettingSpreadsheet.Shared.User", null)
                        .WithMany("Sports")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BettingSpreadsheet.Shared.Tipster", b =>
                {
                    b.HasOne("BettingSpreadsheet.Shared.User", null)
                        .WithMany("Tipsters")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BettingSpreadsheet.Shared.Tipster", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("BettingSpreadsheet.Shared.User", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("Bookies");

                    b.Navigation("Sports");

                    b.Navigation("Tipsters");
                });
#pragma warning restore 612, 618
        }
    }
}
