// <auto-generated />
using System;
using BettingSpreadsheet.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BettingSpreadsheet.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("BettingSpreadsheet.Shared.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BetCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bookie")
                        .HasColumnType("TEXT");

                    b.Property<double>("ClosingOdds")
                        .HasColumnType("REAL");

                    b.Property<string>("League")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("MatchTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Odds")
                        .HasColumnType("REAL");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sport")
                        .HasColumnType("TEXT");

                    b.Property<double>("Stake")
                        .HasColumnType("REAL");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipster")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BetCreated = new DateTime(2021, 3, 15, 19, 31, 30, 510, DateTimeKind.Local).AddTicks(8150),
                            Bookie = "Norsk-Tipping",
                            ClosingOdds = 3.25,
                            League = "Premier League",
                            Locked = false,
                            Match = "Manchester City v Arsenal",
                            MatchDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            MatchTime = new TimeSpan(702905111480),
                            Odds = 3.5,
                            Selection = "Arsenal -0.5 Asian Handicap",
                            Sport = "Football",
                            Stake = 2.0,
                            State = "New",
                            Tipster = "Benny"
                        },
                        new
                        {
                            Id = 2,
                            BetCreated = new DateTime(2021, 3, 15, 19, 31, 30, 511, DateTimeKind.Local).AddTicks(3790),
                            Bookie = "Pinnacle",
                            ClosingOdds = 1.8,
                            League = "Premier League",
                            Locked = true,
                            Match = "West Ham v Fulham",
                            MatchDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            MatchTime = new TimeSpan(702905113790),
                            Odds = 1.8400000000000001,
                            Selection = "Fulham +0.5 Asian Handicap",
                            Sport = "Football",
                            Stake = 5.0,
                            State = "New",
                            Tipster = "Benny"
                        },
                        new
                        {
                            Id = 3,
                            BetCreated = new DateTime(2021, 3, 15, 19, 31, 30, 511, DateTimeKind.Local).AddTicks(3800),
                            Bookie = "Unibet",
                            ClosingOdds = 3.25,
                            League = "Premier League",
                            Locked = true,
                            Match = "Liverpool v Leicester",
                            MatchDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            MatchTime = new TimeSpan(702905113800),
                            Odds = 2.75,
                            Selection = "Leicester -0.5 Asian Handicap",
                            Sport = "Football",
                            Stake = 3.2000000000000002,
                            State = "New",
                            Tipster = "Sondreg"
                        },
                        new
                        {
                            Id = 4,
                            BetCreated = new DateTime(2021, 3, 15, 19, 31, 30, 511, DateTimeKind.Local).AddTicks(3810),
                            Bookie = "Norsk-Tipping",
                            ClosingOdds = 3.25,
                            League = "Premier League",
                            Locked = false,
                            Match = "Tottenham v Manchester Untited",
                            MatchDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            MatchTime = new TimeSpan(702905113810),
                            Odds = 1.5,
                            Selection = "Manchester United -0.5 Asian Handicap",
                            Sport = "Football",
                            Stake = 8.0,
                            State = "New",
                            Tipster = "BookieInsider"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
